### ISSUE TITLE
这个似乎影响效率 使用这个能提升很大 https://github.com/NBXXF/gson_plugin

### ISSUE THREAD

**Issue by NBXXF** [kanyun-inc/Kudos#19]
这个似乎影响效率 使用这个能提升很大 https://github.com/NBXXF/gson_plugin

**Comment by bennyhuo** [comment]
主流应用场景中，Gson、Jackson 在反序列化时基本上是使用反射实现的  Adapter ，我们的目的是为这些主流框架添加空安全和构造器默认值的支持，这样可以实现最小成本迁移。而使用代码生成 Adapter，我们仍然推荐使用 Moshi。

反射方案比生成 Adapter 的方案有个非常大的好处，就是冷启动少了很多 Adapter 的加载耗时。事实上，我们为 JSONReader 提供了生成 IR 的实现，这样可以进一步大幅降低对简单数据的解析耗时。

直接生成 Adapter 在充分预热之后肯定比反射方案有性能优势，不过首次加载的耗时可能需要重点关注。gson_plugin 的思路跟 moshi 接近，不清楚性能上与 moshi 相比在冷启动和充分预热之后相比有多大优势呢？

**Comment by NBXXF** [comment]
> 主流应用场景中，Gson、Jackson 在反序列化时基本上是使用反射实现的 Adapter ，我们的目的是为这些主流框架添加空安全和构造器默认值的支持，这样可以实现最小成本迁移。而使用代码生成 Adapter，我们仍然推荐使用 Moshi。
> 
> 反射方案比生成 Adapter 的方案有个非常大的好处，就是冷启动少了很多 Adapter 的加载耗时。事实上，我们为 JSONReader 提供了生成 IR 的实现，这样可以进一步大幅降低对简单数据的解析耗时。
> 
> 直接生成 Adapter 在充分预热之后肯定比反射方案有性能优势，不过首次加载的耗时可能需要重点关注。gson_plugin 的思路跟 moshi 接近，不清楚性能上与 moshi 相比在冷启动和充分预热之后相比有多大优势呢？

我已经有benchmark数据了
https://github.com/NBXXF/json-benchmark

**Comment by bennyhuo** [comment]
能否也提供一下单次运行考虑加载耗时的性能测试数据？这个对于启动耗时的优化比较关键

**Comment by bennyhuo** [comment]
由于长期没有回复，issue 先关闭了，感谢关注！
