### ISSUE TITLE
kt:1.9.22版本有计划支持吗？   另外BigDecimal类型编译会错误

### ISSUE THREAD

**Issue by qinkangdeid** [kanyun-inc/Kudos#21]
json库：jackson 2.15.2
kotlin版本：1.9.22
使用版本：1.9.20-1.1.1

实体如下：
```kotlin
@Kudos
data class UserReqTest
    (
    val longId: Long,
    val strUsername: String,
    val strCellphone: String,
    val boolActivated: Boolean,
    val intAge:Int?,
    val doubleBalance:Double,
    val bigDecimalHeightInMeters: BigDecimal= BigDecimal.ZERO,
    val listPermissions: List<String> = emptyList(),
    val emptyFavoriteNumbers: List<Int>,
    val localDateTimeBirthDate: LocalDateTime,
    val localDateSignUpDate: LocalDate,
    val mapGenericInfo: Map<String, Any>,
    val nullStr: String? = null
)
```
编译之后报错：

```bash

'java.math.BigDecimal' is not supported by Kudos. Annotate the class with @Kudos or suppress the error by annotating the property with @KudosIgnore.


```

**Comment by bennyhuo** [comment]
1.9.22 是 1.9.20 的 bugfix 版本，一般而言是兼容的，可以直接用 1.9.20-1.1.1。

`java.math.BigDecimal` 应该对反序列化没有实质的影响，后续我们看看能不能从检查中去掉。现在可以先给对应的字段添加 `@KudosIgnore` 来绕过检查，错误信息里面其实有提到哈。

```
'java.math.BigDecimal' is not supported by Kudos. Annotate the class with @Kudos or suppress the error by annotating the property with @KudosIgnore.
```

**Comment by qinkangdeid** [comment]
> 1.9.22 是 1.9.20 的 bugfix 版本，一般而言是兼容的，可以直接用 1.9.20-1.1.1。
> 
> `java.math.BigDecimal` 应该对反序列化没有实质的影响，后续我们看看能不能从检查中去掉。现在可以先给对应的字段添加 `@KudosIgnore` 来绕过检查，错误信息里面其实有提到哈。
> 
> ```
> 'java.math.BigDecimal' is not supported by Kudos. Annotate the class with @Kudos or suppress the error by annotating the property with @KudosIgnore.
> ```

嗯 明白 已经添加`@KudosIgnore`忽略了 感谢回复
